### ISSUE TITLE
Possible for (block for abuse for creating servers)

### ISSUE THREAD

**Issue by mrc4tt** [SoulDemon/MyFreeTeamSpeak-Public#10]
Hey SoulDemon,

Are it's possible for make/added for block of "abuse" for creating multiple servers. [Example blocking for creating multiple account on same IP/per IP]

Let me hear what you recommend.
/Mikkel - aka mkLL11one

**Comment by SoulDemon** [comment]
It already limits 1 account per ip?

**Comment by mrc4tt** [comment]
Ah yeah, sorry! i was visit hospital, so i didnt know anything so much ^^ ;D
