### ISSUE TITLE
Not being able to create a user?

### ISSUE THREAD

**Issue by JayXI** [SoulDemon/MyFreeTeamSpeak-Public#12]
My Config.php is setup as the following

  "db" => array(
      "host" => "localhost",
      "port" => 3306,
      "username" => "root",
      "password" => "Mypassishere",
      "name" => "Ts3", #The Database Name
	  "table" => "users",
      "servers" => "servers", #Server List In Database
      "userservers" => "userservers", #User Servers
      "token_table" => "resettokens",
	  "register_table" => "registerTokens",
      "updateCheck" => "true", #true or false

------------------------------------------------
etc.

But when i got and try to make a login, it doesn't work. it says succeeded but does not allow me to log in.

How to fix?

**Comment by mrc4tt** [comment]
Do you have import the: freets3v2.sql (copy the text in the file) > insert on SQL :)

**Comment by JayXI** [comment]
Yeah, Already done.... still not allowed to do it .-.

**Comment by SoulDemon** [comment]
Some sql servers don't work for some odd reason, still haven't figured it out - used to happen to @MikkelDK dunno what he did to fix it.

**Comment by mrc4tt** [comment]
What OS do you use? - webhosting or own server?

**Comment by SoulDemon** [comment]
I've used four, Windows, Ubuntu, webhosting through cPanel, and a free mysql provider.

**Comment by mrc4tt** [comment]
@SoulDemon - it was to @JayXI  hehe.

Also i dont have problems with my mySQL server (hosted on own server) ^^
- You can use:
  kimsufi.ie (cheap server for mySQL server example!)

**Comment by JayXI** [comment]
I have mySQL server setup on my Fedora VPS. It was working for my other SQL login thing but not for this

**Comment by mrc4tt** [comment]
@JayXI 

Can you post the error/logs to us + screenshot?
