### ISSUE TITLE
config.php

### ISSUE THREAD

**Issue by mrc4tt** [SoulDemon/MyFreeTeamSpeak-Public#13]
Hey @SoulDemon 

Does the config.php automatic resize picture/banner of:
-
  "tooltip" => "", #Icon for tooltip url?
  "hostbutton" => "", #ICON URL
  "iconurl" => "", #ICON GFX
  "banner" => "", #BANNER GFX
  "bannerUrl" => "", #Banner Click URL
-
Example.

**Comment by SoulDemon** [comment]
I dont think it does.

**Comment by mrc4tt** [comment]
//Needed to be checked!

**Comment by mrc4tt** [comment]
//resize was not possible. /closed!
