### ISSUE TITLE
problems with verify email

### ISSUE THREAD

**Issue by mrc4tt** [SoulDemon/MyFreeTeamSpeak-Public#14]
Hey @SoulDemon - I hope you are alive <3 ;)

How does the "verify email" works?

I wont get email example, so dunno how it's needed to be setup of config.php :)

**Comment by SoulDemon** [comment]
Works for gmail, but goes into spam...

**Comment by mrc4tt** [comment]
So it wont needed to be configured? 

Example: gmail.com > username: X@gmail.com etc etc. + password ?

**Comment by SoulDemon** [comment]
so if your website is myfreeteamspeak.tk -> your email would be something like verification@myfreeteamspeak.tk

**Comment by mrc4tt** [comment]
Oh.

It's because (namecheap is so ABIT slow) so i have moved it so one litte server.

So i was hoped it possible for get it works (since i have moved it to: mkh.ovh > it's just DNS/IP without mailserver installed example!)
