### ISSUE TITLE
unable to bind network port

### ISSUE THREAD

**Issue by mrc4tt** [SoulDemon/MyFreeTeamSpeak-Public#15]
The server i have got this problem:

Fatal error: Uncaught exception 'TeamSpeak3_Adapter_ServerQuery_Exception' with message 'unable to bind network port' 

I have whitelisted the all IPs! :)

**Comment by SoulDemon** [comment]
Server already exists on the port its trying to create on.

My panel only works on fresh installs of teamspeak.

**Comment by mrc4tt** [comment]
Possible for change of start ports? I have forget about it possible.

**Comment by mrc4tt** [comment]
\\Fixed! ;)
