### ISSUE TITLE
Change maxservers without to delete database?

### ISSUE THREAD

**Issue by mrc4tt** [SoulDemon/MyFreeTeamSpeak-Public#16]
Hey,

Possible for change maxservers without to delete/insert new database?

[ScreenShot!](https://i.gyazo.com/9c5bb7ee392b961bc2e2dde1317d355d.png)

**Comment by SoulDemon** [comment]
Just do an update query?

**Comment by mrc4tt** [comment]
//Fixed from @SoulDemon <3
