### ISSUE TITLE
still active? :D

### ISSUE THREAD

**Issue by mrc4tt** [SoulDemon/MyFreeTeamSpeak-Public#18]
Are you still active with coding. @SoulDemon ;)

**Comment by SoulDemon** [comment]
If I was to restart the project, it'd be redone from scratch.

**Comment by mrc4tt** [comment]
TeaSpeak Server is the new! :D Do you have try it out. it's a copy of TeamSpeak server. ^^

**Comment by SoulDemon** [comment]
Yes i already have the $100 version of it.

**Comment by mrc4tt** [comment]
Hehe. ;) i have the 10 $ ;P i'm planned to upgrade for 2x 1 years. ;P

**Comment by SoulDemon** [comment]
o.0 aren't you on my discord @MikkelDK

**Comment by mrc4tt** [comment]
My name is mkll11one#2090 :)

**Comment by SoulDemon** [comment]
Added, MyFreeTeamspeak rewrite happening now in nodejs.

**Comment by mrc4tt** [comment]
Nice one. Better system maybe 2019.

**Comment by SoulDemon** [comment]
Maybe, Accept my discord invite <3
