### ISSUE TITLE
Foreach loop error

### ISSUE THREAD

**Issue by DitgerDW** [SoulDemon/MyFreeTeamSpeak-Public#7]
Can't make a server, it gives an error caused by the foreach loop, any way to fix this?

**Comment by mrc4tt** [comment]
Can you post the "error" here? :)

**Comment by DitgerDW** [comment]
![2016-09-12 2](https://cloud.githubusercontent.com/assets/11805730/18442308/8cb85f12-7910-11e6-8ebe-2ad430abb3d6.png)
![2016-09-12](https://cloud.githubusercontent.com/assets/11805730/18442307/8cae8744-7910-11e6-95ae-a1a13bbceddd.png)

In these two there is the error when I click on Create Server
In the other one there is a field error when i try to create one

**Comment by SoulDemon** [comment]
You have to add ts3 query info into the db

**Comment by DitgerDW** [comment]
So I already need to have a server? or where can I find this?
I thought i could run a ts3 server on my website, I'm a beginner, so I only know the basics of HTML and CSS, I don't really know how to fix it

**Comment by SoulDemon** [comment]
When you first run the ts3 server it gives you query information for serveradmin, which you need to add to the db
