### ISSUE TITLE
Help.

### ISSUE THREAD

**Issue by AugustoRubio** [SoulDemon/MyFreeTeamSpeak-Public#8]
Could you give me more specifications of how can I install the panel ?
Can I put the panel on a machine with only hosting and link to a separate server with TS ?

**Comment by SoulDemon** [comment]
```
 "host" => "localhost", # The mysql server ip
  "port" => 3306, #the mysql port
  "username" => "root", #the mysql username
  "password" => "", #the mysql password
  "name" => "freets3v2", #The Database Name
```

in config.php

In the servers table in phpmyadmin, or whatever you use to manage the mysql database add the server?

Don't forget to whitelist your websites ip address per ts server.

**Comment by AugustoRubio** [comment]
Ok I put the information requested in config.php only loading the page is too slow.
And what is the password for the first login?

**Comment by AugustoRubio** [comment]
I really did not understand What you want me to put in the archives to communicate with MYSQL.

**Comment by mrc4tt** [comment]
@Augusto22xb - Do you need help, or does we need to close this issue? :)
