### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alcahuete** [SoulDemon/MyFreeTeamSpeak-Public#9]
Looks like a great project!

I've installed on multiple servers and get the following:
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /home/.../public_html/myts/home.php:2) in /home/.../public_html/myts/Commands/class.logsys.php(1) : eval()'d code on line 265

Also, how do you populate the database with the TS servers?  When I do it manually, it breaks the sidebar.

Thanks!

**Comment by SoulDemon** [comment]
When you do it manually, did you whitelist your webserver? You're teamspeak will ban your webserver ip which causes the freeze.
As for headers: open config.php and change ini_set("display_errors", "on"); to ini_set("display_errors", "off");

**Comment by SoulDemon** [comment]
As for multiple server hosting what hoster are you using? Is it through a cpanel... etc?

**Comment by alcahuete** [comment]
Hi, and thanks a bunch for the quick reply.

I did whitelist the IP.  The webserver is actually on the same IP as the Teamspeak server. 

The errors are gone now, but things still aren't working.

I am the host. :)  It's our own dedicated server.  We have TS servers on several servers.  It does have cPanel on it, yes.

**Comment by SoulDemon** [comment]
Do you have a teamspeak IP I could join? Much easier to help.

**Comment by alcahuete** [comment]
Is there a way to PM you or email you the IP?  I'd prefer not to have it out the public.

**Comment by SoulDemon** [comment]
hop on by the irc @ http://webchat.esper.net/?channels=#MyFreeTeamSpeak
